### ISSUE TITLE
Include "--files-without-matches" in rg-menu

### ISSUE THREAD

**Issue by CsBigDataHub** [dajva/rg.el#106]
Is it possible to include `--files-without-matches` switch in rg-menu?

Info on the switch - https://github.com/BurntSushi/ripgrep/issues/138

**Comment by dajva** [comment]
Thanks for the suggestion. You can actually do this yourself by using the transient menu API https://magit.vc/manual/transient/ to modify the `rg-menu` transient. The API isn't super straight forward to understand though so may need a bit of digging to find out how to do it.

Now I don't think this will work very well since the package isn't expecting files without matching lines as the output from ripgrep. Maybe some combinations of configurations will work but the default is more or less broken.

**Comment by dajva** [comment]
Not on the roadmap to support so closing this.
