### ISSUE TITLE
Is it possible to override a build-in type alias?

### ISSUE THREAD

**Issue by rdeterre** [dajva/rg.el#22]
I am working on a project that contains both `.c` and `.cpp` files. This makes it so that the result of `rg-dwim` is usually incomplete because either `*.c *.h` *or* `*.cpp *.hpp` files are searched depending on the current buffer.

I created a custom type alias that applies to both C and C++ files, but it is not selected by default over the built-in ones. Is there a way to change that?

Thanks

**Comment by dajva** [comment]
The implementation simply extracts the first match and the builtins are listed before the custom ones.
This patch would probably do it:
```
@@ -378,7 +378,7 @@ If NOSPECIAL is non nil the `rg-special-type-aliases' will not be
 included."
   (unless rg-builtin-type-aliases
     (setq rg-builtin-type-aliases (rg-list-builtin-type-aliases)))
-  (append rg-builtin-type-aliases rg-custom-type-aliases
+  (append rg-custom-type-aliases rg-builtin-type-aliases
           (unless nospecial rg-special-type-aliases)))
 
 (defun rg-default-alias ()
```
I think this change makes sense since it is very useful to be able to override the rg internals which we have not control over.
Please try if it solves your problem before we put it on master.

**Comment by rdeterre** [comment]
Thanks for your quick response, the change does work here, that's perfect!

Cheers
