### ISSUE TITLE
Please add a prefix to test-helper.el to avoid conflicts with 68 other packages

### ISSUE THREAD

**Issue by tarsius** [dajva/rg.el#4]
There exist at least 69 packages that contain a file named `test-helper.el` that also provides the feature `test-helper`.

This leads to issues for users who have at least two of these packages installed.  It is unlikely that such a user would be able to run the tests of all of those packages.  If the primary test file of one of those packages does `(require 'test-helper)`, then it is undefined which of the various `test-helper.el` files gets loaded.  Which it is, depends on the order of the `load-path`.

To avoid this conflicts, you should rename your `test-helper.el` to `<your-package>-test-helper.el` and adjust the feature and symbol prefixes accordingly.

Also don't forget to update the `require` form in your primary test file and/or update references to the library/feature elsewhere.  Also, if your primary test file is named something like `test.el`, then please consider renaming that too (same for any other utility elisp files your repositoroy may contain).

Thanks!

PS: This issue is a bit generic because I had to open 69 issues.

**Comment by dajva** [comment]
I think you should blame [ert-runner.el](https://github.com/rejeep/ert-runner.el) for this. These files are created automatically by that package. So probably a good idea to report it there. That would not fix the issues with exisiting packages though.

I thought a bit about this when I started using ert-runner but didn't saw it as a prolem since these files shall not be part of any packages on melpa and usually you will only do development on one package at a time. The main use case is also to run the test from command line in a separate emacs session but sure, you can run the tests from inside emacs if you want to as well.

Now, I am not a very experienced elisp programmer so I am probably overseeing some use case that you are thinking of here. I guess switching between development  of different packages in the same emacs session could be a problem. Do you see other common scenarios where this is a problem?

**Comment by tarsius** [comment]
Thanks for the information. Someone else already pointed this out to me, but you provide some additional details. I am now adding this to all these issues:

---

I've been informed, that `ert-runner` automatically loads the `test-helper.el` file. So you should **not** rename that file. Instead please see [this issue](https://github.com/rejeep/ert-runner.el/issues/38), where I suggest that the `(provide 'test-helper)` should be dropped instead. Please accept my apologize for opening these issues prematurely.
