### ISSUE TITLE
Pad line numbers or align results

### ISSUE THREAD

**Issue by net** [dajva/rg.el#44]
An option to pad line numbers or otherwise align results would be useful. Likewise, an option to change or hide the line number separator (currently a `:`) would help reduce visual clutter.

```
Unaligned:
5:fifth line
15:fifteenth line

Aligned:
 5:fifth line
15:fifteenth line

Custom separator:
 5┊fifth line
15┊fifteenth line
```

**Comment by dajva** [comment]
I have just played around with this a bit but this is currently my plan.

Add a custom variable `rg-match-pos-separator` (naming to be decided) that can control the character used as separator. Using space here would "hide" it.
Also adding custom variable `rg-align-match-pos` that turns on/off alignment.

Default algnment to be decided but probably 5 digits for line and 3 for column. That would allow for about 100000 lines and 1000 columns to look good. That should be enough for most cases but I will also add custom varables for these values so that the alignment could be tweaked.

**Comment by net** [comment]
I'm excited to hear that!

Do you think a default of 4 or even 3 for line alignment would be sufficient? I suspect searching a file with 100,000 lines is a fairly rare case for most users that can be configured for if desired.

**Comment by dajva** [comment]
Unfortunately this breaks `wgrep` support so currently on hold although the implementation is essentially finished.

There are also more problems with `wgrep-ag` with a stalled solution upstream: https://github.com/mhayashi1120/Emacs-wgrep/issues/41

Possible solution would be to fork `wgrep-ag` into this package and do local fixes here.

**Comment by dajva** [comment]
I've pushed a test branch with this feature. Needs a bit of fixing but you can try it out if you want. Will take a bit of time before this is merged to master.

**Comment by dajva** [comment]
Merged to master.
