### ISSUE TITLE
When I open one of these options, the bottom window always appears

### ISSUE THREAD

**Issue by e190** [dajva/rg.el#64]
![图片](https://user-images.githubusercontent.com/39932163/66461393-8862e300-eaab-11e9-9fd1-dd6583d0e2c1.png)
I don't know why the bottom window what's "unknown" always appears when you open one of these options

**Comment by dajva** [comment]
Looks like this is MS Windows. I can't officially support windows since I don't have a windows system for testing, unfortunately. I am happy to fix this or accept a PR if we can find the source of the problem though.

The main problem seems to be that the file name isn't recognized. The heading should be `File: .\path\to\file.el` if it was recognized correctly. The file names are detected with the color codes exported by the `ripgrep` binary so I suspect that your binary outputs non standard color codes.
Maybe this is a windows issue or could also be a ripgrep version issue. The matches seems to be higligted correctly so it partly works at least.

1. Which version of this package are you using?
2. Can you post the output of command line `rg --version` invokation?
3. Can you post me the raw output (including color escape sequences) of this search:
```
rg <some-search-with-matches> --heading --color=always
```
4. The expected fg color of the filenames is magenta so you could also try to invoke `rg` with the universal argument (`C-u`) and add `--colors path:fg:magenta` to the command line and see if that fixes the problem.

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/66467309-d6311880-eab6-11e9-804d-43d23b4bf345.png)
package:   rg-20190925.543

**Comment by dajva** [comment]
Ok, so the file headings are blue instead of magenta. Have you configured this globally or is this a windows thing?
Anyway, this can be fixed by letting this package be more explicit about the colors that is needed.
I will prepare a fix.

**Comment by e190** [comment]
![图片](https://user-images.githubusercontent.com/39932163/66469031-b3543380-eab9-11e9-906e-aedc76d7470f.png)
I'm now setting path, which is a problem with Windows 7 and works fine with Linux.

**Comment by dajva** [comment]
Should be fixed on master now. Please let me know if the issue remains.

**Comment by e190** [comment]
awesome.Your patch fixes our problem.So Thanks .
