### ISSUE TITLE
Is there a way to sort the files?

### ISSUE THREAD

**Issue by tspiteri** [dajva/rg.el#80]
Ripgrep does have an option, but it is not exposed and I think with good reason, as it inhibits rigprep parallelism. However sometimes having the result buffer sorted by file would help my flow; is there a way to sort the files inside the result buffer once rg is finished?

**Comment by dajva** [comment]
There is no easy way to sort an existing result since the result buffer is only text and no datastructure is available to work on unfortunately. You can make use of the `rg` flag though.
There are several ways to go about this:
- The `--sort` flag is actually exposed although not super easy to find. It's part of the transient popup menu but hidden by default behind transient level 5. You can expose it by changing the default transient level to 5 (`C-x l C-x l 5` when in the menu) or modify the level for the flag to have it in your default setup. See [here](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html#Enabling-and-Disabling-Suffixes) for the details.
- Define a toggle command. This would allow you toggle this flag with choosen key binding in the results buffer. Not that flexible but if you mainly want to sort on path it's an option. See [here](https://rgel.readthedocs.io/en/latest/configuration.html#function-rg-define-toggle) for more info.
- Creare your own search command with this flag on: See [here](https://rgel.readthedocs.io/en/latest/configuration.html#function-rg-define-search).

**Comment by tspiteri** [comment]
Thanks! `(rg-define-toggle "--sort path" "o")` is perfectly fine for my use. It allows me to pass whatever flags I want to rg; it can't be much more flexible than that :)
