### ISSUE TITLE
Running `rg` commands don't give any results 

### ISSUE THREAD

**Issue by kirill-gerasimenko** [dajva/rg.el#98]
Hi, 

I'm using emacs version `27.1.50` on Pop_OS linux. `rg` version is `11.0.2`. `rg` config is simple - I just enable `rg-menu`.
When I invoke any `rg.el` command, providing necessary arguments - I get no results in the output `*rg*` buffer. No errors or anything unusuall, but there are no results.
If I use the command (that is printed in `*rg*` buffer and run it from the `bash` in the target directory - I get plenty of results as it should be. 
For example: 
![image](https://user-images.githubusercontent.com/3036330/94365576-66a2a780-00d2-11eb-98d0-13dadd57769b.png)

How would I troubleshoot such issue? 

Thanks!

**Comment by dajva** [comment]
Hmm, that seems weird. 
Since the ripgrep binary doesn't give any output I would guess that it something in the emacs environment that is to blame.
I would try running the same command through emacs grep (`M-x grep`) to see if you get any output. If not, that would rule out this package.
You could also try to add the target directory to the end of the command line (also through emacs grep) to rule out problems with `default-diretory`.

**Comment by kirill-gerasimenko** [comment]
I've found the issue. 

`(setq process-connection-type 'null)` - I had this set to `null` in my config 🤷‍♂️
